import type { TreeSelectProps } from 'tdesign-react';
export const options: TreeSelectProps['data'] = [

  {
    label: '北京市',
    value: 'beijing',
    children: [],
  },
  {
    label: '天津市',
    value: 'tianjin',
    children: [],
  },
  {
    label: '上海市',
    value: 'shanghai',
    children: [],
  },
  {
    label: '重庆市',
    value: 'chongqing',
    children: [],
  },
  {
    label: '河北省',
    value: 'hebei',
    children: [
      { label: '石家庄市', value: 'shijiazhuang' },
      { label: '唐山市', value: 'tangshan' },
      { label: '秦皇岛市', value: 'qinhuangdao' },
      { label: '邯郸市', value: 'handan' },
      { label: '邢台市', value: 'xingtai' },
      { label: '保定市', value: 'baoding' },
      { label: '张家口市', value: 'zhangjiakou' },
      { label: '承德市', value: 'chengde' },
      { label: '沧州市', value: 'cangzhou' },
      { label: '廊坊市', value: 'langfang' },
      { label: '衡水市', value: 'hengshui' },
    ],
  },
  {
    label: '山西省',
    value: 'shanxi',
    children: [
      { label: '太原市', value: 'taiyuan' },
      { label: '大同市', value: 'datong' },
      { label: '阳泉市', value: 'yangquan' },
      { label: '长治市', value: 'changzhi' },
      { label: '晋城市', value: 'jincheng' },
      { label: '朔州市', value: 'shuozhou' },
      { label: '晋中市', value: 'jinzhong' },
      { label: '运城市', value: 'yuncheng' },
      { label: '忻州市', value: 'xinzhou' },
      { label: '临汾市', value: 'linfen' },
      { label: '吕梁市', value: 'lvliang' },
    ],
  },
  {
    label: '辽宁省',
    value: 'liaoning',
    children: [
      { label: '沈阳市', value: 'shenyang' },
      { label: '大连市', value: 'dalian' },
      { label: '鞍山市', value: 'anshan' },
      { label: '抚顺市', value: 'fushun' },
      { label: '本溪市', value: 'benxi' },
      { label: '丹东市', value: 'dandong' },
      { label: '锦州市', value: 'jinzhou' },
      { label: '营口市', value: 'yingkou' },
      { label: '阜新市', value: 'fuxin' },
      { label: '辽阳市', value: 'liaoyang' },
      { label: '盘锦市', value: 'panjin' },
      { label: '铁岭市', value: 'tieling' },
      { label: '朝阳市', value: 'chaoyang' },
      { label: '葫芦岛市', value: 'huludao' },
    ],
  },
  {
    label: '吉林省',
    value: 'jilin',
    children: [
      { label: '长春市', value: 'changchun' },
      { label: '吉林市', value: 'jilin' },
      { label: '四平市', value: 'siping' },
      { label: '辽源市', value: 'liaoyuan' },
      { label: '通化市', value: 'tonghua' },
      { label: '白山市', value: 'baishan' },
      { label: '松原市', value: 'songyuan' },
      { label: '白城市', value: 'baicheng' },
      { label: '延边朝鲜族自治州', value: 'yanbian' },
    ],
  },
  {
    label: '黑龙江省',
    value: 'heilongjiang',
    children: [
      { label: '哈尔滨市', value: 'harbin' },
      { label: '齐齐哈尔市', value: 'qiqihar' },
      { label: '鸡西市', value: 'jixi' },
      { label: '鹤岗市', value: 'hegang' },
      { label: '双鸭山市', value: 'shuangyashan' },
      { label: '大庆市', value: 'daqing' },
      { label: '伊春市', value: 'yichun' },
      { label: '佳木斯市', value: 'jiamusi' },
      { label: '七台河市', value: 'qitaihe' },
      { label: '牡丹江市', value: 'mudanjiang' },
      { label: '黑河市', value: 'heihe' },
      { label: '绥化市', value: 'suihua' },
      { label: '大兴安岭地区', value: 'daxinganling' },
    ],
  },
  {
    label: '江苏省',
    value: 'jiangsu',
    children: [
      { label: '南京市', value: 'nanjing' },
      { label: '无锡市', value: 'wuxi' },
      { label: '徐州市', value: 'xuzhou' },
      { label: '常州市', value: 'changzhou' },
      { label: '苏州市', value: 'suzhou' },
      { label: '南通市', value: 'nantong' },
      { label: '连云港市', value: 'lianyungang' },
      { label: '淮安市', value: 'huaian' },
      { label: '盐城市', value: 'yancheng' },
      { label: '扬州市', value: 'yangzhou' },
      { label: '镇江市', value: 'zhenjiang' },
      { label: '泰州市', value: 'taizhou' },
      { label: '宿迁市', value: 'suqian' },
    ],
  },
  {
    label: '浙江省',
    value: 'zhejiang',
    children: [
      { label: '杭州市', value: 'hangzhou' },
      { label: '宁波市', value: 'ningbo' },
      { label: '温州市', value: 'wenzhou' },
      { label: '嘉兴市', value: 'jiaxing' },
      { label: '湖州市', value: 'huzhou' },
      { label: '绍兴市', value: 'shaoxing' },
      { label: '金华市', value: 'jinhua' },
      { label: '衢州市', value: 'quzhou' },
      { label: '舟山市', value: 'zhoushan' },
      { label: '台州市', value: 'taizhou_zj' },
      { label: '丽水市', value: 'lishui' },
    ],
  },
  {
    label: '安徽省',
    value: 'anhui',
    children: [
      { label: '合肥市', value: 'hefei' },
      { label: '芜湖市', value: 'wuhu' },
      { label: '蚌埠市', value: 'bengbu' },
      { label: '淮南市', value: 'huainan' },
      { label: '马鞍山市', value: 'maanshan' },
      { label: '淮北市', value: 'huaibei' },
      { label: '铜陵市', value: 'tongling' },
      { label: '安庆市', value: 'anqing' },
      { label: '黄山市', value: 'huangshan' },
      { label: '滁州市', value: 'chuzhou' },
      { label: '阜阳市', value: 'fuyang' },
      { label: '宿州市', value: 'suzhou_ah' },
      { label: '六安市', value: 'liuan' },
      { label: '亳州市', value: 'bozhou' },
      { label: '池州市', value: 'chizhou' },
      { label: '宣城市', value: 'xuancheng' },
    ],
  },
  {
    label: '福建省',
    value: 'fujian',
    children: [
      { label: '福州市', value: 'fuzhou' },
      { label: '厦门市', value: 'xiamen' },
      { label: '莆田市', value: 'putian' },
      { label: '三明市', value: 'sanming' },
      { label: '泉州市', value: 'quanzhou' },
      { label: '漳州市', value: 'zhangzhou' },
      { label: '南平市', value: 'nanping' },
      { label: '龙岩市', value: 'longyan' },
      { label: '宁德市', value: 'ningde' },
    ],
  },
  {
    label: '江西省',
    value: 'jiangxi',
    children: [
      { label: '南昌市', value: 'nanchang' },
      { label: '景德镇市', value: 'jingdezhen' },
      { label: '萍乡市', value: 'pingxiang' },
      { label: '九江市', value: 'jiujiang' },
      { label: '新余市', value: 'xinyu' },
      { label: '鹰潭市', value: 'yingtan' },
      { label: '赣州市', value: 'ganzhou' },
      { label: '吉安市', value: 'jian' },
      { label: '宜春市', value: 'yichun_jx' },
      { label: '抚州市', value: 'fuzhou_jx' },
      { label: '上饶市', value: 'shangrao' },
    ],
  },
  {
    label: '山东省',
    value: 'shandong',
    children: [
      { label: '济南市', value: 'jinan' },
      { label: '青岛市', value: 'qingdao' },
      { label: '淄博市', value: 'zibo' },
      { label: '枣庄市', value: 'zaozhuang' },
      { label: '东营市', value: 'dongying' },
      { label: '烟台市', value: 'yantai' },
      { label: '潍坊市', value: 'weifang' },
      { label: '济宁市', value: 'jining' },
      { label: '泰安市', value: 'taian' },
      { label: '威海市', value: 'weihai' },
      { label: '日照市', value: 'rizhao' },
      { label: '临沂市', value: 'linyi' },
      { label: '德州市', value: 'dezhou' },
      { label: '聊城市', value: 'liaocheng' },
      { label: '滨州市', value: 'binzhou' },
      { label: '菏泽市', value: 'heze' },
    ],
  },
  {
    label: '河南省',
    value: 'henan',
    children: [
      { label: '郑州市', value: 'zhengzhou' },
      { label: '开封市', value: 'kaifeng' },
      { label: '洛阳市', value: 'luoyang' },
      { label: '平顶山市', value: 'pingdingshan' },
      { label: '安阳市', value: 'anyang' },
      { label: '鹤壁市', value: 'hebi' },
      { label: '新乡市', value: 'xinxiang' },
      { label: '焦作市', value: 'jiaozuo' },
      { label: '濮阳市', value: 'puyang' },
      { label: '许昌市', value: 'xuchang' },
      { label: '漯河市', value: 'luohe' },
      { label: '三门峡市', value: 'sanmenxia' },
      { label: '南阳市', value: 'nanyang' },
      { label: '商丘市', value: 'shangqiu' },
      { label: '信阳市', value: 'xinyang' },
      { label: '周口市', value: 'zhoukou' },
      { label: '驻马店市', value: 'zhumadian' },
    ],
  },
  {
    label: '湖北省',
    value: 'hubei',
    children: [
      { label: '武汉市', value: 'wuhan' },
      { label: '黄石市', value: 'huangshi' },
      { label: '十堰市', value: 'shiyan' },
      { label: '宜昌市', value: 'yichang' },
      { label: '襄阳市', value: 'xiangyang' },
      { label: '鄂州市', value: 'ezhou' },
      { label: '荆门市', value: 'jingmen' },
      { label: '孝感市', value: 'xiaogan' },
      { label: '荆州市', value: 'jingzhou' },
      { label: '黄冈市', value: 'huanggang' },
      { label: '咸宁市', value: 'xianning' },
      { label: '随州市', value: 'suizhou' },
      { label: '恩施土家族苗族自治州', value: 'enshi' },
    ],
  },
  {
    label: '湖南省',
    value: 'hunan',
    children: [
      { label: '长沙市', value: 'changsha' },
      { label: '株洲市', value: 'zhuzhou' },
      { label: '湘潭市', value: 'xiangtan' },
      { label: '衡阳市', value: 'hengyang' },
      { label: '邵阳市', value: 'shaoyang' },
      { label: '岳阳市', value: 'yueyang' },
      { label: '常德市', value: 'changde' },
      { label: '张家界市', value: 'zhangjiajie' },
      { label: '益阳市', value: 'yiyang' },
      { label: '郴州市', value: 'chenzhou' },
      { label: '永州市', value: 'yongzhou' },
      { label: '怀化市', value: 'huaihua' },
      { label: '娄底市', value: 'loudi' },
      { label: '湘西土家族苗族自治州', value: 'xiangxi' },
    ],
  },
  {
    label: '广东省',
    value: 'guangdong',
    children: [
      { label: '广州市', value: 'guangzhou' },
      { label: '韶关市', value: 'shaoguan' },
      { label: '深圳市', value: 'shenzhen' },
      { label: '珠海市', value: 'zhuhai' },
      { label: '汕头市', value: 'shantou' },
      { label: '佛山市', value: 'foshan' },
      { label: '江门市', value: 'jiangmen' },
      { label: '湛江市', value: 'zhanjiang' },
      { label: '茂名市', value: 'maoming' },
      { label: '肇庆市', value: 'zhaoqing' },
      { label: '惠州市', value: 'huizhou' },
      { label: '梅州市', value: 'meizhou' },
      { label: '汕尾市', value: 'shanwei' },
      { label: '河源市', value: 'heyuan' },
      { label: '阳江市', value: 'yangjiang' },
      { label: '清远市', value: 'qingyuan' },
      { label: '东莞市', value: 'dongguan' },
      { label: '中山市', value: 'zhongshan' },
      { label: '潮州市', value: 'chaozhou' },
      { label: '揭阳市', value: 'jieyang' },
      { label: '云浮市', value: 'yunfu' },
    ],
  },
  {
    label: '海南省',
    value: 'hainan',
    children: [
      { label: '海口市', value: 'haikou' },
      { label: '三亚市', value: 'sanya' },
      { label: '三沙市', value: 'sansha' },
      { label: '儋州市', value: 'danzhou' },
      { label: '五指山市', value: 'wuzhishan' },
      { label: '琼海市', value: 'qionghai' },
      { label: '文昌市', value: 'wenchang' },
      { label: '万宁市', value: 'wanning' },
      { label: '东方市', value: 'dongfang' },
      { label: '定安县', value: 'dingan' },
      { label: '屯昌县', value: 'tunchang' },
      { label: '澄迈县', value: 'chengmai' },
      { label: '临高县', value: 'lingao' },
      { label: '白沙黎族自治县', value: 'baisha' },
      { label: '昌江黎族自治县', value: 'changjiang' },
      { label: '乐东黎族自治县', value: 'ledong' },
      { label: '陵水黎族自治县', value: 'lingshui' },
      { label: '保亭黎族苗族自治县', value: 'baoting' },
      { label: '琼中黎族苗族自治县', value: 'qiongzhong' },
    ],
  },
  {
    label: '四川省',
    value: 'sichuan',
    children: [
      { label: '成都市', value: 'chengdu' },
      { label: '自贡市', value: 'zigong' },
      { label: '攀枝花市', value: 'panzhihua' },
      { label: '泸州市', value: 'luzhou' },
      { label: '德阳市', value: 'deyang' },
      { label: '绵阳市', value: 'mianyang' },
      { label: '广元市', value: 'guangyuan' },
      { label: '遂宁市', value: 'suining' },
      { label: '内江市', value: 'neijiang' },
      { label: '乐山市', value: 'leshan' },
      { label: '南充市', value: 'nanchong' },
      { label: '眉山市', value: 'meishan' },
      { label: '宜宾市', value: 'yibin' },
      { label: '广安市', value: 'guangan' },
      { label: '达州市', value: 'dazhou' },
      { label: '雅安市', value: 'yaan' },
      { label: '巴中市', value: 'bazhong' },
      { label: '资阳市', value: 'ziyang' },
      { label: '阿坝藏族羌族自治州', value: 'aba' },
      { label: '甘孜藏族自治州', value: 'ganzi' },
      { label: '凉山彝族自治州', value: 'liangshan' },
    ],
  },
  {
    label: '贵州省',
    value: 'guizhou',
    children: [
      { label: '贵阳市', value: 'guiyang' },
      { label: '六盘水市', value: 'liupanshui' },
      { label: '遵义市', value: 'zunyi' },
      { label: '安顺市', value: 'anshun' },
      { label: '毕节市', value: 'bijie' },
      { label: '铜仁市', value: 'tongren' },
      { label: '黔西南布依族苗族自治州', value: 'qianxinan' },
      { label: '黔东南苗族侗族自治州', value: 'qiandongnan' },
      { label: '黔南布依族苗族自治州', value: 'qiannan' },
    ],
  },
  {
    label: '云南省',
    value: 'yunnan',
    children: [
      { label: '昆明市', value: 'kunming' },
      { label: '曲靖市', value: 'qujing' },
      { label: '玉溪市', value: 'yuxi' },
      { label: '保山市', value: 'baoshan' },
      { label: '昭通市', value: 'zhaotong' },
      { label: '丽江市', value: 'lijiang' },
      { label: '普洱市', value: 'puer' },
      { label: '临沧市', value: 'lincang' },
      { label: '楚雄彝族自治州', value: 'chuxiong' },
      { label: '红河哈尼族彝族自治州', value: 'honghe' },
      { label: '文山壮族苗族自治州', value: 'wenshan' },
      { label: '西双版纳傣族自治州', value: 'xishuangbanna' },
      { label: '大理白族自治州', value: 'dali' },
      { label: '德宏傣族景颇族自治州', value: 'dehong' },
      { label: '怒江傈僳族自治州', value: 'nujiang' },
      { label: '迪庆藏族自治州', value: 'diqing' },
    ],
  },
  {
    label: '陕西省',
    value: 'shaanxi',
    children: [
      { label: '西安市', value: 'xian' },
      { label: '铜川市', value: 'tongchuan' },
      { label: '宝鸡市', value: 'baoji' },
      { label: '咸阳市', value: 'xianyang' },
      { label: '渭南市', value: 'weinan' },
      { label: '延安市', value: 'yanan' },
      { label: '汉中市', value: 'hanzhong' },
      { label: '榆林市', value: 'yulin' },
      { label: '安康市', value: 'ankang' },
      { label: '商洛市', value: 'shangluo' },
    ],
  },
  {
    label: '甘肃省',
    value: 'gansu',
    children: [
      { label: '兰州市', value: 'lanzhou' },
      { label: '嘉峪关市', value: 'jiayuguan' },
      { label: '金昌市', value: 'jinchang' },
      { label: '白银市', value: 'baiyin' },
      { label: '天水市', value: 'tianshui' },
      { label: '武威市', value: 'wuwei' },
      { label: '张掖市', value: 'zhangye' },
      { label: '平凉市', value: 'pingliang' },
      { label: '酒泉市', value: 'jiuquan' },
      { label: '庆阳市', value: 'qingyang' },
      { label: '定西市', value: 'dingxi' },
      { label: '陇南市', value: 'longnan' },
      { label: '临夏回族自治州', value: 'linxia' },
      { label: '甘南藏族自治州', value: 'gannan' },
    ],
  },
  {
    label: '青海省',
    value: 'qinghai',
    children: [
      { label: '西宁市', value: 'xining' },
      { label: '海东市', value: 'haidong' },
      { label: '海北藏族自治州', value: 'haibei' },
      { label: '黄南藏族自治州', value: 'huangnan' },
      { label: '海南藏族自治州', value: 'hainan_qh' },
      { label: '果洛藏族自治州', value: 'guoluo' },
      { label: '玉树藏族自治州', value: 'yushu' },
      { label: '海西蒙古族藏族自治州', value: 'haixi' },
    ],
  },
];